name: Imputation-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ucsc-liftover=377
  - plink=1.90b6.12
  - admixture=1.3.0
  - perl=5.26.2
  - bcftools=1.9
  - bioconductor-limma=3.44
  - bioconductor-BSgenome.Hsapiens.UCSC.hg38=1.4.3
  - r-dplyr=1.0.0
  - r-viridis=0.5.1
  - r-readxl=1.3.1
  - r-doParallel=1.0.15
  - r-ggplotify=0.0.5
  - r-hexbin=1.28.1
  - r-data.table=1.12.8